server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/khj_blog
    username: khj
    password: khj
    driver-class-name: com.mysql.cj.jdbc.Driver


